(ns app.generator.bila.regis
  (:require [app.generator.bila.biology.bioteknologi]
            [app.generator.bila.biology.klasifikasi_organisme]
            [app.generator.bila.biology.evolusi]
            [app.generator.bila.biology.biokimia]))

(def register
  [{:folder "evolusi"
    :file   "bio-analogi-dan-homologi-01.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.evolusi/bio-analogi-dan-homologi-01}
   {:folder "biokimia"
    :file   "bio-karbohidrat-3-03.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.biokimia/bio-karbohidrat-3-03}
   {:folder "biokimia"
    :file   "bio-lipid-2-01.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.biokimia/bio-lipid-2-01}
   {:folder "biokimia"
    :file   "bio-protein-2-01.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.biokimia/bio-protein-2-01}
   {:folder "biokimia"
    :file   "bio-lipid-3-02.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.biokimia/bio-lipid-3-02}
   {:folder "biokimia"
    :file   "bio-protein-3-01.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.biokimia/bio-protein-3-01}
   {:folder "biokimia"
    :file   "bio-protein-3-02.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.biokimia/bio-protein-3-02}
   {:folder "klasifikasi_organisme"
    :file   "bio-evolusi-tumbuhan-akuatik-ke-terestrial-01.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.klasifikasi_organisme/bio-evolusi-tumbuhan-akuatik-ke-terestrial-01}
   {:folder "klasifikasi_organisme"
    :file   "bio-evolusi-tumbuhan-akuatik-ke-terestrial-02.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.klasifikasi_organisme/bio-evolusi-tumbuhan-akuatik-ke-terestrial-02}
   {:folder "evolusi"
    :file   "bio-beda-reproduksi-seksual-dan-aseksual.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.evolusi/bio-beda-reproduksi-seksual-dan-aseksual}
   {:folder "klasifikasi_organisme"
    :file   "bio-organ-sensoris-Condrichthyes.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.klasifikasi_organisme/bio-organ-sensoris-Condrichthyes}
   {:folder "klasifikasi_organisme"
    :file   "bio-reptilia-1-struktur-dasar.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.klasifikasi_organisme/bio-reptilia-1-struktur-dasar}
   {:folder "klasifikasi_organisme"
    :file   "bio-struktur-amniotic-egg-01.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.klasifikasi_organisme/bio-struktur-amniotic-egg-01}
   {:folder "klasifikasi_organisme"
    :file   "bio-pembelahan-biner-bakteri.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.klasifikasi_organisme/bio-pembelahan-biner-bakteri}
   {:folder "klasifikasi_organisme"
    :file   "bio-pembentukan-tunas-bakteri.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.klasifikasi_organisme/bio-pembentukan-tunas-bakteri}
   {:folder "klasifikasi_organisme"
    :file   "bio-fragmentasi-bakteri.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.klasifikasi_organisme/bio-fragmentasi-bakteri}
   {:folder "klasifikasi_organisme"
    :file   "bio-transformasi-bakteri.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.klasifikasi_organisme/bio-transformasi-bakteri}
   {:folder "klasifikasi_organisme"
    :file   "bio-transduksi-bakteri.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.klasifikasi_organisme/bio-transduksi-bakteri}
   {:folder "klasifikasi_organisme"
    :file   "bio-konjugasi-bakteri.html"
    :topic  :biology
    :gen-fn app.generator.bila.biology.klasifikasi_organisme/bio-konjugasi-bakteri}])